export interface RoadCard {
  id: string;
  title: string;
  description: string;
  ageMin: number;
  ageMax: number;
  emoji: string;
  tags: string[];
}

export const ROAD_A_CARDS: RoadCard[] = [
  {
    id: 'a-1',
    title: '60대에 순자산 10억 만들기',
    description: '지금부터 꾸준히 모으면 60대에 10억이 가능해요. 현실적인 경로를 확인해보세요.',
    ageMin: 30,
    ageMax: 55,
    emoji: '💰',
    tags: ['자산형성', '장기투자'],
  },
  {
    id: 'a-2',
    title: '50대에 조기은퇴(FIRE) 하기',
    description: '경제적 자유를 일찍 달성하는 FIRE 전략을 계산해드려요.',
    ageMin: 30,
    ageMax: 52,
    emoji: '🔥',
    tags: ['FIRE', '조기은퇴'],
  },
  {
    id: 'a-11',
    title: '집을 줄여 현금을 만들어볼까요?',
    description: '큰 집을 줄이면 노후 현금이 얼마나 생길지 시뮬레이션해드려요.',
    ageMin: 50,
    ageMax: 75,
    emoji: '🏠',
    tags: ['다운사이징', '부동산'],
  },
  {
    id: 'a-3',
    title: '내 집 마련까지 얼마나?',
    description: '목표 지역과 예산으로 내 집 마련까지 걸리는 기간을 계산해요.',
    ageMin: 20,
    ageMax: 45,
    emoji: '🔑',
    tags: ['내집마련', '부동산'],
  },
  {
    id: 'a-4',
    title: '은퇴 후 월 300만원 생활 유지',
    description: '은퇴 후에도 월 300만원 생활을 유지하려면 얼마가 필요할까요?',
    ageMin: 45,
    ageMax: 70,
    emoji: '📊',
    tags: ['은퇴설계', '생활비'],
  },
  {
    id: 'a-5',
    title: '자녀 교육비 미리 준비하기',
    description: '초·중·고·대학까지 예상 교육비를 미리 계산하고 준비해요.',
    ageMin: 30,
    ageMax: 55,
    emoji: '🎓',
    tags: ['교육비', '자녀계획'],
  },
  {
    id: 'a-6',
    title: '지출을 줄여 비상금 만들기',
    description: '고정비를 분석하고 6개월치 비상금 마련까지의 경로를 안내해요.',
    ageMin: 0,
    ageMax: 999,
    emoji: '🛡️',
    tags: ['비상금', '지출관리'],
  },
  {
    id: 'a-7',
    title: '여행 다니면서 노후 준비하기',
    description: '여행 비용을 포함한 노후 예산으로 실현 가능한 계획을 세워요.',
    ageMin: 20,
    ageMax: 55,
    emoji: '✈️',
    tags: ['여행', '라이프스타일'],
  },
  {
    id: 'a-8',
    title: '창업 자금을 준비하고 싶어요',
    description: '창업 목표 금액과 시기까지 얼마를 어떻게 모아야 하는지 계산해요.',
    ageMin: 20,
    ageMax: 50,
    emoji: '🚀',
    tags: ['창업', '목돈마련'],
  },
  {
    id: 'a-10',
    title: '지금 대출을 갚으면 얼마나 빨라질까요?',
    description: '대출 상환 시나리오별 노후 자산 차이를 비교해드려요.',
    ageMin: 20,
    ageMax: 65,
    emoji: '🏦',
    tags: ['대출상환', '이자절약'],
  },
  {
    id: 'a-12',
    title: '결혼 자금을 준비하고 싶어요',
    description: '결혼 목표 시기까지 필요한 저축액과 경로를 안내해드려요.',
    ageMin: 20,
    ageMax: 38,
    emoji: '💍',
    tags: ['결혼준비', '목돈마련'],
  },
  {
    id: 'a-14',
    title: '아이 태어나기 전에 준비해요',
    description: '출산·육아 첫 3년 비용과 보험·저축 준비를 미리 계획해요.',
    ageMin: 25,
    ageMax: 42,
    emoji: '👶',
    tags: ['출산준비', '육아비용'],
  },
  {
    id: 'a-15',
    title: '자녀에게 얼마를 남길 수 있을까요?',
    description: '노후를 충분히 쓰고도 자녀에게 남길 수 있는 자산을 계산해요.',
    ageMin: 50,
    ageMax: 75,
    emoji: '🤝',
    tags: ['상속', '자녀지원'],
  },
  {
    id: 'a-16',
    title: '퇴직금을 가장 유리하게 받는 방법',
    description: '일시금 vs IRP vs 연금, 세후 수령액을 비교해드려요.',
    ageMin: 45,
    ageMax: 65,
    emoji: '💼',
    tags: ['퇴직금', '절세'],
  },
  {
    id: 'a-17',
    title: '노후 의료비를 대비하고 싶어요',
    description: '65세 이후 예상 의료비와 필요한 보험·준비금을 분석해요.',
    ageMin: 50,
    ageMax: 75,
    emoji: '🏥',
    tags: ['의료비', '건강보험'],
  },
  {
    id: 'a-18',
    title: '자녀 독립 자금을 주고도 내 노후는?',
    description: '자녀에게 일정 금액을 지원한 후의 노후 자산 흐름을 보여드려요.',
    ageMin: 45,
    ageMax: 65,
    emoji: '🏡',
    tags: ['자녀지원', '노후설계'],
  },
  {
    id: 'a-19',
    title: '수익률에 따라 노후가 얼마나 달라질까요?',
    description: '연 6%·8%·10%·12% 수익률 시나리오를 한눈에 비교해요.',
    ageMin: 20,
    ageMax: 55,
    emoji: '📈',
    tags: ['수익률비교', '투자전략'],
  },
  {
    id: 'a-20',
    title: '세금을 줄이는 절세 전략이 궁금해요',
    description: 'IRP·ISA·연금저축으로 절세하는 방법과 절감 금액을 계산해요.',
    ageMin: 30,
    ageMax: 65,
    emoji: '📋',
    tags: ['절세', 'IRP', 'ISA'],
  },
  {
    id: 'a-b1',
    title: '배우자가 먼저 떠나면 내 노후는?',
    description: '배우자 사망 후 홀로 생활하는 시나리오의 노후 자산을 분석해요.',
    ageMin: 55,
    ageMax: 80,
    emoji: '🕊️',
    tags: ['위험대비', '홀로노후'],
  },
  {
    id: 'a-b2',
    title: '직장 그만두면 건보료가 얼마나 오를까요?',
    description: '직장 건보에서 지역 건보로 바뀔 때 예상 보험료를 계산해요.',
    ageMin: 30,
    ageMax: 65,
    emoji: '💊',
    tags: ['건강보험', '퇴직준비'],
  },
];
